version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: eeg2025-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: eeg2025
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    command: mongod --wiredTigerCacheSizeGB 1.5
    networks:
      - eeg2025-network

  redis:
    image: redis:7.2-alpine
    container_name: eeg2025-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 60 1000
      --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - eeg2025-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: eeg2025-redis-ui
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - eeg2025-network

  mongo-express:
    image: mongo-express:latest
    container_name: eeg2025-mongo-ui
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass123
    depends_on:
      - mongodb
    networks:
      - eeg2025-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  redis_data:
    driver: local

networks:
  eeg2025-network:
    driver: bridge
